### ISSUE TITLE
SRUMECmd Errors encountered?

### ISSUE THREAD

**Issue by EricZimmerman** [WithSecureLabs/slide-decks#4]
Funny, I don't recall getting told about any as it relates to SRUMECmd

Maybe open an issue so it can be looked at vs a driveby mention like this that provides no context?

Please tell me the 'errors' we're not just about known tables.

**Comment by EricZimmerman** [comment]
Also it's just a matter of time before you run into issues with parsing. Same with replying on libvshadow for shadow copies. It gets them wrong. The think is, you won't know it when it happens. 

This is why I didn't go that route: accuracy.

**Comment by catarinadf** [comment]
Hi Eric,

Thanks for raising the issue and sorry for the delay in the response. On the slide that mentions the SrumECmd error, the issue we encountered is that the tool does not properly process SRUDB.dat databases from Windows Server 2022 due to the tables being unknown, and therefore ignored (e.g., SDP Volume Provider)

![srumecmd_error_win_server_2022](https://github.com/WithSecureLabs/slide-decks/assets/41592444/cc554abd-c2e4-4585-8477-9bb6e9b059a0)

Best regards,
Catarina.
